server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lgx123

mybatis:
  type-aliases-package: com.example.bootdemo.bean
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com.example.bootdemo.mapper: DEBUG